services:
  serverspsqldb:
    image: postgres:latest
    container_name: serverspsqldb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dailytasks
    ports:
      - "5433:5432"
    networks:
      - servers-network

  node-express:
    build:
      context: ./node-express
      dockerfile: Dockerfile
    container_name: node-express-container
    ports:
      - "12341:12791"
    environment:
      DB_USER: postgres
      DB_HOST: serverspsqldb
      DB_NAME: dailytasks
      DB_PASSWORD: root
      DB_PORT: 5432
      SERVER_PORT: 12791
    networks:
      - servers-network

networks:
  servers-network:
    driver: bridge
