services:
  bun-elysia:
    build:
      context: ./bun-elysia
      dockerfile: Dockerfile
    container_name: bun-elysia-server
    ports:
      - "1011:1011"
    environment:
      DB_USER: hologic
      DB_HOST: gdds-educational-site-db-1
      DB_NAME: dailytasks
      DB_PASSWORD: hologic
      DB_PORT: 5432
      SERVER_PORT: 1011
    networks:
      - servers-network

  bun-hono:
    build:
      context: ./bun-hono
      dockerfile: Dockerfile
    container_name: bun-hono-server
    ports:
      - "9101:9910"
    environment:
      DB_USER: hologic
      DB_HOST: gdds-educational-site-db-1
      DB_NAME: dailytasks
      DB_PASSWORD: hologic
      DB_PORT: 5432
      SERVER_PORT: 9910
    networks:
      - servers-network

  node-express:
    build:
      context: ./node-express
      dockerfile: Dockerfile
    container_name: node-express-server
    ports:
      - "1234:12791"
    environment:
      DB_USER: hologic
      DB_HOST: gdds-educational-site-db-1
      DB_NAME: dailytasks
      DB_PASSWORD: hologic
      DB_PORT: 5432
      SERVER_PORT: 12791
    networks:
      - servers-network

  node-fastify:
    build:
      context: ./node-fastify
      dockerfile: Dockerfile
    container_name: node-fastify-server
    ports:
      - "5678:5678"
    environment:
      DB_USER: hologic
      DB_HOST: gdds-educational-site-db-1
      DB_NAME: dailytasks
      DB_PASSWORD: hologic
      DB_PORT: 5432
      SERVER_PORT: 5678
    networks:
      - servers-network

networks:
  servers-network:
    driver: bridge
