services:
  postgresdb:
    image: postgres:latest
    container_name: postgresdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dailytasks
    ports:
      - "5432:5432"
    networks:
      - servers-network

  bun-hono:
    build:
      context: ./bun-hono
      dockerfile: Dockerfile
    container_name: bun-hono-container
    ports:
      - "1234:1234"
    environment:
      DB_USER: postgres
      DB_HOST: postgresdb
      DB_NAME: dailytasks
      DB_PASSWORD: root
      DB_PORT: 5432
      SERVER_PORT: 1234
    networks:
      - servers-network

  node-express:
    build:
      context: ./node-express
      dockerfile: Dockerfile
    container_name: node-express-container
    ports:
      - "4567:4567"
    environment:
      DB_USER: postgres
      DB_HOST: postgresdb
      DB_NAME: dailytasks
      DB_PASSWORD: root
      DB_PORT: 5432
      SERVER_PORT: 4567
    networks:
      - servers-network

  node-fastify:
    build:
      context: ./node-fastify
      dockerfile: Dockerfile
    container_name: node-fastify-container
    ports:
      - "8910:8910"
    environment:
      DB_USER: postgres
      DB_HOST: postgresdb
      DB_NAME: dailytasks
      DB_PASSWORD: root
      DB_PORT: 5432
      SERVER_PORT: 8910
    networks:
      - servers-network

  bun-elysia:
    build:
      context: ./bun-elysia
      dockerfile: Dockerfile
    container_name: bun-elysia-container
    ports:
      - "1112:1112"
    environment:
      DB_USER: postgres
      DB_HOST: postgresdb
      DB_NAME: dailytasks
      DB_PASSWORD: root
      DB_PORT: 5432
      SERVER_PORT: 1112
    networks:
      - servers-network

networks:
  servers-network:
    driver: bridge
